import React from 'react';
import { AlertTriangle } from 'lucide-react';

export default function LegalDisclaimer() {
  return (
    <div className="bg-amber-50 border border-amber-200 rounded-2xl p-4 text-amber-900 flex items-start space-x-3 shadow-sm">
      <AlertTriangle className="w-5 h-5 text-amber-600 mt-0.5 flex-shrink-0" />
      <div>
        <h4 className="font-bold text-amber-950 text-xs uppercase tracking-wider">IMPORTANT LEGAL DISCLAIMER</h4>
        <p className="text-xs text-amber-900 mt-1 leading-relaxed font-medium">
          This system provides general legal information for educational and reference purposes only. 
          Information generated by this assistant does <strong>NOT</strong> constitute professional legal advice. 
          Public users do not have access to verified case documents or confidential RAG databases.
        </p>
      </div>
    </div>
  );
}
