"""
RAG Phase 4 — Answer Service
==============================
Orchestrates the full RAG pipeline:

  query + user_id + conversation_history
    → retrieve_relevant_chunks()      (Phase 3 retrieval)
    → build_context()                 (Phase 4 context builder)
    → GeminiService.generate()        (if valid key)
    → fallback: grounded free engine  (if Gemini unavailable)
    → RAGAnswerResult

Multi-turn context
------------------
Callers may pass `conversation_history` (list of {"role": str, "content": str}
dicts) which is prepended to the prompt so the AI understands prior turns.
History is capped by config (CHAT_MAX_HISTORY_MESSAGES / CHAT_MAX_HISTORY_CHARS)
before being injected — the service trusts the caller to pre-trim.

Security
--------
user_id is passed directly to retrieve_relevant_chunks() which enforces
owner_id == user_id at the SQL level. This service never bypasses that.

Fallback guarantee
------------------
The free engine ALWAYS receives the retrieved context. It never returns
generic legal info when documents are available — it tells the user the
document does not contain enough information instead.
"""

import logging
from dataclasses import dataclass, field
from typing import List, Optional, Dict

from sqlalchemy.orm import Session

from app.core.config import settings
from app.services.retrieval.retrieval_service import retrieve_relevant_chunks, SearchResult
from app.services.rag.context_builder import (
    build_context,
    build_system_prompt,
    build_full_prompt,
)
from app.services.ai.gemini_service import GeminiService, get_gemini_api_key

logger = logging.getLogger(__name__)

DISCLAIMER = (
    "\n\n---\n*Legal Disclaimer: This response is generated by an AI system for "
    "informational purposes only and does not constitute formal legal advice. "
    "Please consult a qualified legal professional for case-specific counsel.*"
)


# ── result dataclass ──────────────────────────────────────────────────────────

@dataclass
class SourceItem:
    chunk_id:    str
    document_id: int
    filename:    str
    page_number: Optional[int]
    similarity:  float
    matter_id:   Optional[str] = None
    jurisdiction: Optional[str] = None


@dataclass
class RAGAnswerResult:
    answer:            str
    sources:           List[SourceItem] = field(default_factory=list)
    used_rag:          bool = False
    provider_used:     str  = "Free AI Legal Engine"
    chunks_retrieved:  int  = 0
    no_relevant_context: bool = False


# ── helpers ───────────────────────────────────────────────────────────────────

def _is_valid_gemini_key(key: str) -> bool:
    return bool(key) and key.startswith("AIzaSy")


def _sources_from_results(results: List[SearchResult]) -> List[SourceItem]:
    return [
        SourceItem(
            chunk_id=    r.chunk_id,
            document_id= r.document_id,
            filename=    r.filename,
            page_number= r.page_number,
            similarity=  r.similarity,
            matter_id=   r.matter_id,
            jurisdiction=r.jurisdiction,
        )
        for r in results
    ]


def _grounded_fallback(query: str, context: str, results: List[SearchResult]) -> str:
    """
    Free engine grounded on retrieved context.
    If context is available, try to answer from it.
    If not, clearly say so — never hallucinate.
    """
    if not context:
        return (
            "**No Relevant Document Context Found**\n\n"
            "I could not find sufficiently relevant information in your uploaded "
            "documents to answer this question.\n\n"
            "> **[General Legal Information]** — If you need a general answer, "
            "please use the Tier 1 Public Assistant instead.\n\n"
            "_If you have uploaded a relevant document, try reprocessing it or "
            "check that embeddings were generated successfully._"
            + DISCLAIMER
        )

    # Build a grounded answer from context
    lines = [
        "## Answer Based on Your Document\n",
        "Based on the retrieved sections from your uploaded document(s):\n",
    ]

    for i, r in enumerate(results[:settings.RAG_MAX_CONTEXT_CHUNKS], start=1):
        snippet = r.content[:400].strip()
        lines.append(
            f"**Source {i} — {r.filename} (Page {r.page_number or 'N/A'}, "
            f"Similarity: {r.similarity:.0%})**\n"
            f"> {snippet}{'...' if len(r.content) > 400 else ''}\n"
        )

    lines.append(
        "\n**Analysis:**\n"
        "The above extracted sections are the most relevant passages from your "
        "document related to your question. Review them carefully in context of "
        f"your query: *\"{query}\"*\n\n"
        "> For a more detailed AI-generated interpretation, please configure a "
        "valid Google Gemini API key in the system settings."
    )
    lines.append(DISCLAIMER)
    return "\n".join(lines)


# ── history helpers ───────────────────────────────────────────────────────────

def _build_history_block(history: Optional[List[Dict[str, str]]]) -> str:
    """
    Convert a list of {"role": ..., "content": ...} dicts into a
    plaintext conversation history block for injection into the prompt.

    Hard caps applied here as a safety net:
    - At most CHAT_MAX_HISTORY_MESSAGES turns
    - Total chars capped at CHAT_MAX_HISTORY_CHARS
    """
    if not history:
        return ""

    max_msgs  = getattr(settings, "CHAT_MAX_HISTORY_MESSAGES", 20)
    max_chars = getattr(settings, "CHAT_MAX_HISTORY_CHARS", 8000)

    # Take only the most-recent turns
    trimmed = history[-max_msgs:]

    lines  = []
    total  = 0
    for turn in trimmed:
        role    = turn.get("role", "user").capitalize()
        content = turn.get("content", "").strip()
        if not content:
            continue
        line = f"{role}: {content}"
        if total + len(line) > max_chars:
            break
        lines.append(line)
        total += len(line) + 1

    if not lines:
        return ""
    return "CONVERSATION HISTORY (most recent turns):\n" + "\n".join(lines)


def _build_prompt_with_history(query: str, context: str, history_block: str) -> str:
    """
    Build the full user-facing prompt including prior conversation context
    (when available) and the retrieved document context.
    """
    parts = []
    if history_block:
        parts.append(history_block)
        parts.append("---")
    parts.append(f"RETRIEVED DOCUMENT CONTEXT:\n\n{context}")
    parts.append("---")
    parts.append(f"USER QUESTION:\n{query}")
    parts.append("Please answer the question using the document context above."
                 + (" Consider the conversation history for context." if history_block else ""))
    return "\n\n".join(parts)


# ── main function ─────────────────────────────────────────────────────────────

def rag_answer(
    query:       str,
    user_id:     int,
    db:          Session,
    document_id: Optional[int] = None,
    top_k:       Optional[int] = None,
    conversation_history: Optional[List[Dict[str, str]]] = None,
) -> RAGAnswerResult:
    """
    Full RAG pipeline:
      retrieve → build context → inject history → generate answer → return with sources.

    Parameters
    ----------
    query                : user's natural-language question
    user_id              : current_user.id  (enforced in retrieval SQL)
    db                   : SQLAlchemy session
    document_id          : optional — restrict retrieval to one document
    top_k                : override default RAG_TOP_K
    conversation_history : optional list of {"role": "user"|"assistant", "content": str}
                           representing the recent turns before this message.
                           History is capped before injection so context window is never blown.

    Returns
    -------
    RAGAnswerResult with answer, sources, provider_used, flags
    """
    clean_query = query.strip()
    if not clean_query:
        return RAGAnswerResult(
            answer="Please provide a valid question.",
            no_relevant_context=True,
        )

    _top_k = top_k if top_k is not None else settings.RAG_TOP_K

    # ── Step 1: Retrieve relevant chunks ─────────────────────────────────────
    logger.info("RAG answer: user=%d doc_id=%s", user_id, document_id)

    results = retrieve_relevant_chunks(
        query=       clean_query,
        user_id=     user_id,
        db=          db,
        document_id= document_id,
        top_k=       _top_k,
        threshold=   settings.RAG_SIMILARITY_THRESHOLD,
    )

    sources = _sources_from_results(results)

    # ── Step 2: Build document context ───────────────────────────────────────
    context = build_context(results)

    # ── Step 3: No relevant context → early return ────────────────────────────
    if not results:
        return RAGAnswerResult(
            answer=(
                "**No Relevant Information Found**\n\n"
                "I could not find sufficiently relevant information in your uploaded "
                "documents to answer this question.\n\n"
                "**Possible reasons:**\n"
                "- The document may not cover this topic\n"
                "- The document may not have been processed yet (check embeddings)\n"
                "- Try rephrasing your question with specific terms from the document\n\n"
                "> *For general legal information, use the Tier 1 Public Assistant.*"
                + DISCLAIMER
            ),
            sources=[],
            used_rag=False,
            provider_used="System",
            chunks_retrieved=0,
            no_relevant_context=True,
        )

    # ── Step 4: Build history block ───────────────────────────────────────────
    history_block = _build_history_block(conversation_history)

    # ── Step 5: Try Gemini ────────────────────────────────────────────────────
    api_key = get_gemini_api_key()
    answer  = None

    if _is_valid_gemini_key(api_key):
        try:
            system_prompt  = build_system_prompt()
            user_prompt    = _build_prompt_with_history(clean_query, context, history_block)
            gemini         = GeminiService(api_key=api_key)
            gemini_answer  = gemini.generate_response(
                prompt=             user_prompt,
                system_instruction= system_prompt,
                temperature=        0.1,
            )
            if gemini_answer and not gemini_answer.startswith("[Google Gemini API Error"):
                answer        = gemini_answer + DISCLAIMER
                provider_used = "Google Gemini AI"
                logger.info("Gemini answered RAG query for user=%d", user_id)
        except Exception as exc:
            logger.warning("Gemini failed for RAG query: %s", exc)

    # ── Step 6: Fallback — grounded free engine ───────────────────────────────
    if not answer:
        answer        = _grounded_fallback(clean_query, context, results)
        provider_used = "LexGuard Free Legal Engine (Grounded)"

    return RAGAnswerResult(
        answer=           answer,
        sources=          sources,
        used_rag=         True,
        provider_used=    provider_used,
        chunks_retrieved= len(results),
        no_relevant_context=False,
    )
